-- Haskell data types for the abstract syntax.
-- Generated by the BNF converter.

module AbsLambdaNatNEW where

newtype Id = Id String
  deriving (Eq, Ord, Show, Read)

data Program = Prog Exp
  deriving (Eq, Ord, Show, Read)

data Exp = EAbs Id Exp | EApp Exp Exp | EVar Id | ENatS Exp | ENatO
  deriving (Eq, Ord, Show, Read)

